In [1]:
import cv2
import dlib

# load the face detector and shape predictor
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("models/shape_predictor_68_face_landmarks.dat")

In [2]:
import os
import numpy as np
np.set_printoptions(threshold=np.inf)


# Import module yang digunkaan untuk ekstrak gambar
from preprocessing.input_to_image import get_frames_by_input_video
from preprocessing.scarpping_component import extract_component_by_images
# from preprocessing.feature_extraction import  block_matching

pathDatasetImage = "dataset/video_to_images"
get_frames_by_input_video(pathInputVideo="dataset/video/EP02_01f.avi", pathOutputImage=pathDatasetImage, framePerSecond=60)

# looping semua file yang ada didalam
for filename in os.listdir(pathDatasetImage):
    if filename.endswith(".jpg") or filename.endswith(".png"): 
        # Create the directory if it doesn't exist
        image = cv2.imread(os.path.join(pathDatasetImage, filename))
        image = cv2.resize(image, (600, 500))
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # detect the faces
        rects = detector(gray)

        # go through the face bounding boxes
        for rect in rects:
            # apply the shape predictor to the face ROI
            shape = predictor(gray, rect)

            # X itu kiri ke kanan
            # Y itu atas ke bawah

            # Mata Kiri
            data_blocks = np.array(extract_component_by_images(
                image=image, 
                shape=shape, 
                frameName=filename.split(".")[0],
                objectName="eye_left", 
                objectRectangle={"x_right": 39, "x_left": 36, "y_highest": 38, "y_lowest": 41}, 
                pixelShifting={"pixel_x": 25, "pixel_y": 25},
            ))
            print(data_blocks)

            # # Mata Kanan
            # extract_component_by_images(
            #     image=image, 
            #     shape=shape, 
            #     frameName=filename.split(".")[0],
            #     objectName="eye_right", 
            #     objectRectangle={"x_right": 45, "x_left": 42, "y_highest": 43, "y_lowest": 47}, 
            #     pixelShifting={"pixel_x": 25, "pixel_y": 25}
            # )

            # # Alis Kiri
            # extract_component_by_images(
            #     image=image, 
            #     shape=shape, 
            #     frameName=filename.split(".")[0],
            #     objectName="eyebrow_left", 
            #     objectRectangle={"x_right": 21, "x_left": 17, "y_highest": 18, "y_lowest": 21}, 
            #     pixelShifting={"pixel_x": 15, "pixel_y": 15}
            # )

            # # Alis Kanan
            # extract_component_by_images(
            #     image=image, 
            #     shape=shape, 
            #     frameName=filename.split(".")[0],
            #     objectName="eyebrow_right", 
            #     objectRectangle={"x_right": 26, "x_left": 22, "y_highest": 25, "y_lowest": 22}, 
            #     pixelShifting={"pixel_x": 15, "pixel_y": 15}
            # )

            # # Mulut
            # extract_component_by_images(
            #     image=image, 
            #     shape=shape, 
            #     frameName=filename.split(".")[0],
            #     objectName="mouth", 
            #     objectRectangle={"x_right": 54, "x_left": 48, "y_highest": 52, "y_lowest": 57}, 
            #     pixelShifting={"pixel_x": 25, "pixel_y": 5}
            # )

            # # Hidung Kanan
            # extract_component_by_images(
            #     image=image, 
            #     shape=shape, 
            #     frameName=filename.split(".")[0],
            #     objectName="nose_right", 
            #     objectRectangle={"x_right": 31, "x_left": 40, "y_highest": 40, "y_lowest": 48}, 
            #     pixelShifting={"pixel_x": 15, "pixel_y": -25}
            # )

            # # Hidung Kiri
            # extract_component_by_images(
            #     image=image, 
            #     shape=shape, 
            #     frameName=filename.split(".")[0],
            #     objectName="nose_left", 
            #     objectRectangle={"x_right": 47, "x_left": 35, "y_highest": 47, "y_lowest": 54}, 
            #     pixelShifting={"pixel_x": 15, "pixel_y": -25}
            # )
            
            # tambah component disini

# cv2.imshow("Frame", image)
# cv2.waitKey(0)


frame1-Eye_left
[[[[150 150 150 150 150 150 150]
   [150 135 134 132 127 121 127]
   [150 136 134 132 127 122 122]
   [150 137 135 132 128 125 121]
   [150 135 133 131 129 128 121]
   [150 131 128 126 127 129 122]
   [150 126 123 121 123 128 124]]

  [[150 150 150 150 150 150 150]
   [124 122 124 128 131 130 130]
   [120 118 120 124 128 130 129]
   [119 118 119 122 125 126 122]
   [121 121 121 120 120 119 115]
   [123 123 120 117 114 113 110]
   [124 122 118 113 110 110 112]]

  [[150 150 150 150 150 150 150]
   [131 131 129 127 123 120 119]
   [127 127 127 126 124 122 120]
   [120 123 126 128 127 124 121]
   [113 119 126 129 128 125 122]
   [110 116 123 127 126 124 122]
   [113 116 119 121 122 122 121]]

  [[150 150 150 150 150 150 150]
   [119 115 112 111 113 118 123]
   [127 123 117 113 110 110 112]
   [125 124 120 116 111 111 112]
   [116 118 119 118 118 120 124]
   [119 122 125 124 124 127 132]
   [127 130 131 129 126 129 135]]

  [[150 150 150 150 150 150 150]
   [123 119 112 10